import {
  ChatInputCommandInteraction,
  EmbedBuilder,
  SlashCommandBuilder,
  SlashCommandOptionsOnlyBuilder,
} from "discord.js";
import { Command } from "./CommandInterface";
import { ConfigManager } from "../ConfigManager";
import { PrismaUtils } from "../util/PrismaUtils";
import { generatePersonalSeasonWrapped } from "../logic/seasonRecap/PersonalSeasonWrapped";

export default class WrappedCommand implements Command {
  public name = "wrapped";
  public description = "Generate your personal season recap.";
  public buttonIds: string[] = [];
  public data: SlashCommandOptionsOnlyBuilder;

  constructor() {
    this.data = new SlashCommandBuilder()
      .setName(this.name)
      .setDescription(this.description)
      .addIntegerOption((option) =>
        option
          .setName("season")
          .setDescription("Season number to recap (default: current season)")
          .setRequired(false)
      );
  }

  async execute(interaction: ChatInputCommandInteraction): Promise<void> {
    await interaction.deferReply();

    const player = await PrismaUtils.findPlayer(interaction.user.id);
    if (!player) {
      await interaction.editReply("Player not found. Use /register first.");
      return;
    }

    const seasonNumber =
      interaction.options.getInteger("season") ??
      ConfigManager.getConfig().season;

    try {
      const wrapped = await generatePersonalSeasonWrapped({
        seasonNumber,
        playerId: player.id,
      });

      if (!wrapped) {
        await interaction.editReply(
          `No wrapped stats found for you in Season ${seasonNumber}.`
        );
        return;
      }

      const avatarUrl =
        interaction.member && "displayAvatarURL" in interaction.member
          ? interaction.member.displayAvatarURL()
          : interaction.user.displayAvatarURL();
      const embed = new EmbedBuilder()
        .setColor("#1DB954")
        .setTitle(wrapped.title)
        .setDescription(wrapped.description)
        .setThumbnail(avatarUrl)
        .addFields(wrapped.fields)
        .setFooter({
          text: `${wrapped.footer} • Generated by ${interaction.user.tag}`,
          iconURL: interaction.user.displayAvatarURL(),
        })
        .setTimestamp();

      await interaction.editReply({ embeds: [embed] });
    } catch (error) {
      if (error instanceof Error && error.message.includes("not found")) {
        await interaction.editReply(`Season #${seasonNumber} not found.`);
        return;
      }
      throw error;
    }
  }
}
